# Generated by Django 4.2.1 on 2023-05-05 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 15, 30, 32, 514044)),
        ),
    ]
